require: rubocop-rspec

AllCops:
  NewCops: enable
  UseCache: true
  TargetRubyVersion: 3.1
Layout/LineLength:
  Max: 150
Metrics/AbcSize:
  Max: 20
Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
Metrics/MethodLength:
  Max: 15
Naming/MethodParameterName:
  Enabled: false
RSpec/ExampleLength:
  Max: 15
RSpec/FilePath:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
Style/Documentation:
  Enabled: false
